// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkfebIDHLN14JI_gXJwBq16X1izmfx7gc',
    appId: '1:869851254456:web:00fa619e83bc0c1b572e4d',
    messagingSenderId: '869851254456',
    projectId: 'rampi-1a52d',
    authDomain: 'rampi-1a52d.firebaseapp.com',
    storageBucket: 'rampi-1a52d.appspot.com',
    measurementId: 'G-MVCDGB5T8T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBwRPrMec8frQo3p3HMM5wudCDe6DpFCEM',
    appId: '1:869851254456:android:6737ff2303fcab53572e4d',
    messagingSenderId: '869851254456',
    projectId: 'rampi-1a52d',
    storageBucket: 'rampi-1a52d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDYp8CaNdgm-z3--jMS-u-HzTiitkrFdn0',
    appId: '1:869851254456:ios:0c6b5bdceb1d2004572e4d',
    messagingSenderId: '869851254456',
    projectId: 'rampi-1a52d',
    storageBucket: 'rampi-1a52d.appspot.com',
    iosBundleId: 'com.example.rampiMapeador',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDYp8CaNdgm-z3--jMS-u-HzTiitkrFdn0',
    appId: '1:869851254456:ios:c1753bf94927ed30572e4d',
    messagingSenderId: '869851254456',
    projectId: 'rampi-1a52d',
    storageBucket: 'rampi-1a52d.appspot.com',
    iosBundleId: 'com.example.rampiMapeador.RunnerTests',
  );
}
